export const SPORTS_DATA = {
  LiveMatches: [
    {
      sportType: "Football",
      leagues: [
        "England Premier League",
        "England EFL Cup",
        "International Clubs UEFA Champions League",
        "International Africa Cup of Nations",
        "International Euro Cup",
        "Spain Laliga",
        "Italy Series A",
      ],
      odds: [
        "Over/Under",
        "Draw No Bet",
        "3 Way & O/U",
        "Total Goals",
        "Double Chance",
        "Handicapped",
      ],
      sportsLeagues: [
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 1,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 2,
              time: "00:24",
              teamOne: "Equatorial Guinea",
              teamTwo: "South African",
              teamOneScore: "0",
              teamTwoScore: "3",
              home: "2",
              draw: "1.7",
              away: "2.1",
            },
          ],
        },
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 3,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 4,
              time: "08:00",
              teamOne: "Namibia",
              teamTwo: "Moroco",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "2.2",
            },
            {
              id: 5,
              time: "06:00",
              teamOne: "Mail",
              teamTwo: "DR Congo",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 6,
              time: "11:23",
              teamOne: "Nigeria",
              teamTwo: "Moroco",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Fri Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 7,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 8,
              time: "21:23",
              teamOne: "Guinea",
              teamTwo: "Egypt",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "3.0",
              draw: "1.0",
              away: "2.23",
            },
          ],
        },
        {
          leagueName: "International Euro Cup",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 9,
              time: "00:23",
              teamOne: "Switzerland",
              teamTwo: "Germany",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 10,
              time: "00:24",
              teamOne: "Scotland",
              teamTwo: "Hungary",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "International Euro Cup",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 11,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "International Euro Cup",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 12,
              time: "08:00",
              teamOne: "Croatia",
              teamTwo: "Italy",
              teamOneScore: "1",
              teamTwoScore: "0",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 13,
              time: "06:00",
              teamOne: "Spain",
              teamTwo: "Albania",
              teamOneScore: "4",
              teamTwoScore: "2",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 20,
              time: "11:23",
              teamOne: "Denmark",
              teamTwo: "England",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },
        {
          leagueName: "England Premier League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 21,
              time: "00:23",
              teamOne: "Switzerland",
              teamTwo: "Germany",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 20,
              time: "00:24",
              teamOne: "Scotland",
              teamTwo: "Hungary",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "England Premier League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 17,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "England Premier League",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 18,
              time: "08:00",
              teamOne: "Croatia",
              teamTwo: "Italy",
              teamOneScore: "1",
              teamTwoScore: "0",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 19,
              time: "06:00",
              teamOne: "Spain",
              teamTwo: "Albania",
              teamOneScore: "4",
              teamTwoScore: "2",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 20,
              time: "11:23",
              teamOne: "Denmark",
              teamTwo: "England",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },
        {
          leagueName: "England EFL Cup",
          date: "Fri Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 21,
              time: "19:45",
              teamOne: "Arsenal",
              teamTwo: "Manchester City",
              teamOneScore: "1",
              teamTwoScore: "2",
              home: "2.3",
              draw: "3.4",
              away: "2.5",
            },
            {
              id: 22,
              time: "20:21",
              teamOne: "Chelsea",
              teamTwo: "Tottenham Hotspur",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "1.8",
              draw: "3.0",
              away: "3.2",
            },
          ],
        },
        {
          leagueName: "Spain Laliga",
          date: "Fri Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 23,
              time: "18:30",
              teamOne: "Barcelona",
              teamTwo: "Real Madrid",
              teamOneScore: "3",
              teamTwoScore: "1",
              home: "1.9",
              draw: "3.2",
              away: "4.0",
            },
            {
              id: 24,
              time: "19:00",
              teamOne: "Atletico Madrid",
              teamTwo: "Sevilla",
              teamOneScore: "1",
              teamTwoScore: "1",
              home: "2.0",
              draw: "3.0",
              away: "3.5",
            },
          ],
        },
        {
          leagueName: "Italy Series A",
          date: "Fri Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 25,
              time: "17:00",
              teamOne: "Juventus",
              teamTwo: "AC Milan",
              teamOneScore: "2",
              teamTwoScore: "2",
              home: "2.2",
              draw: "2.8",
              away: "3.0",
            },
            {
              id: 26,
              time: "18:00",
              teamOne: "Inter Milan",
              teamTwo: "Napoli",
              teamOneScore: "3",
              teamTwoScore: "1",
              home: "1.8",
              draw: "3.2",
              away: "3.5",
            },
          ],
        },
      ],
    },

    {
      sportType: "Basketball",
      leagues: [
        "NBA",
        "WNBA",
        "NBA G League",
        "NBA 2K League",
        "Basketball Africa League",
      ],
      odds: ["Over/Under", "Draw No Bet", "Double Chance", "Handicapped"],
      sportsLeagues: [
        {
          leagueName: "NBA",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 27,
              time: "00:23",
              teamOne: "Caltics",
              teamTwo: "Bucks",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 28,
              time: "00:24",
              teamOne: "76ers",
              teamTwo: "Knicks",
              teamOneScore: "0",
              teamTwoScore: "3",
              home: "2",
              draw: "1.7",
              away: "2.1",
            },
          ],
        },
        {
          leagueName: "NBA",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 29,
              time: "00:23",
              teamOne: "Cavailiers",
              teamTwo: "Pacers",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "NBA",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 30,
              time: "08:00",
              teamOne: "Heat",
              teamTwo: "Magic",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "2.2",
            },
            {
              id: 31,
              time: "06:00",
              teamOne: "Bulls",
              teamTwo: "Hawks",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 31,
              time: "11:23",
              teamOne: "Raptors",
              teamTwo: "Hormets",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "NBA",
          date: "Fri Jan 4 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 32,
              time: "00:23",
              teamOne: "Parces",
              teamTwo: "Cavailiers",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 33,
              time: "21:23",
              teamOne: "Magic",
              teamTwo: "Heat",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "3.0",
              draw: "1.0",
              away: "2.23",
            },
            {
              id: 34,
              time: "21:23",
              teamOne: "Wizards",
              teamTwo: "Pistons",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "3.0",
              draw: "1.0",
              away: "2.23",
            },
          ],
        },
        {
          leagueName: "WNBA",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 35,
              time: "21:05",
              teamOne: "Washington Mystics",
              teamTwo: "New York Liberty W",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 36,
              time: "21:24",
              teamOne: "Connecticut Sun W",
              teamTwo: "Indiana Fever W",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "WNBA",
          date: "Thu Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 37,
              time: "08:00",
              teamOne: "Las Vegas Aces W",
              teamTwo: "Phonenix Mercury W",
              teamOneScore: "1",
              teamTwoScore: "0",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 38,
              time: "06:00",
              teamOne: "Seattle Storm W",
              teamTwo: "Minnesota Lynx W",
              teamOneScore: "4",
              teamTwoScore: "2",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 39,
              time: "11:23",
              teamOne: "Dallas Wings W",
              teamTwo: "Chicago Sky W",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },

        {
          leagueName: "NBA G League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 40,
              time: "00:23",
              teamOne: "Minnesota Lynx W",
              teamTwo: "Seatle Storm",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 41,
              time: "00:24",
              teamOne: "Atlanta Dream",
              teamTwo: "Dallas Wing",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "NBA G League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 42,
              time: "00:23",
              teamOne: "Grand Rapids Gold",
              teamTwo: "Motor City Cruise",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "NBA G League",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 43,
              time: "08:00",
              teamOne: "Wisconsin Herd",
              teamTwo: "Windy City Bulls",
              teamOneScore: "22",
              teamTwoScore: "20",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 44,
              time: "06:00",
              teamOne: "Motor City Cruise",
              teamTwo: "Lowa Wolves",
              teamOneScore: "12",
              teamTwoScore: "10",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 45,
              time: "11:23",
              teamOne: "College Park Skyhawks",
              teamTwo: "Delaware Blue Coats",
              teamOneScore: "32",
              teamTwoScore: "11",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },
        {
          leagueName: "NBA 2K League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 46,
              time: "13:00",
              teamOne: "Warriors Gamming Squad",
              teamTwo: "T-Wolves Gaming",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "1.1",
              draw: "2.0",
              away: "1.5",
            },
            {
              id: 47,
              time: "17:30",
              teamOne: "Arsenal",
              teamTwo: "Pistons GT",
              teamOneScore: "1",
              teamTwoScore: "2",
              home: "1.2",
              draw: "0.0",
              away: "1.0",
            },
            {
              id: 48,
              time: "19:30",
              teamOne: "Pacers Gaming",
              teamTwo: "Gizz Gaming",
              teamOneScore: "2",
              teamTwoScore: "2",
              home: "1.20",
              draw: "5.0",
              away: "4.5",
            },
            {
              id: 49,
              time: "17:30",
              teamOne: "Dux Infinitos",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "1.2",
              draw: "0.0",
              away: "1.0",
            },
            {
              id: 50,
              time: "20:00",
              teamOne: "Lakers Gaming",
              teamTwo: "Kings Guard Gaming",
              teamOneScore: "7",
              teamTwoScore: "0",
              home: "2.3",
              draw: "4.0",
              away: "3.5",
            },
          ],
        },
        {
          leagueName: "NBA 2K League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 51,
              time: "00:00",
              teamOne: "Galatasaray",
              teamTwo: "BSC Young Boys",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 52,
              time: "00:00",
              teamOne: "SSC Napoli",
              teamTwo: "Braga",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },

        {
          leagueName: "Basketball Africa League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 53,
              time: "13:00",
              teamOne: "Petro Atletico",
              teamTwo: "Al Ahly",
              teamOneScore: "28",
              teamTwoScore: "12",
              home: "1.1",
              draw: "2.0",
              away: "1.5",
            },
            {
              id: 54,
              time: "17:30",
              teamOne: "SLAC",
              teamTwo: "City Oiler",
              teamOneScore: "1",
              teamTwoScore: "2",
              home: "1.2",
              draw: "0.0",
              away: "1.0",
            },
          ],
        },
        {
          leagueName: "Basketball Africa League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 55,
              time: "00:00",
              teamOne: "Douanes",
              teamTwo: "RES",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 56,
              time: "00:00",
              teamOne: "Abidjan",
              teamTwo: "Monastir",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
      ],
    },

    {
      sportType: "Table Tennis",
      leagues: [],
      odds: [],
      sportsLeagues: [],
    },

    {
      sportType: "Basketball",
      leagues: [],
      odds: [],
      sportsLeagues: [],
    },

    {
      sportType: "Rugby",
      leagues: [],
      odds: [],
      sportsLeagues: [],
    },

    {
      sportType: "Ice Hockey",
      leagues: [],
      odds: [],
      sportsLeagues: [],
    },

    {
      sportType: "Volleyball",
      leagues: [],
      odds: [],
      sportsLeagues: [],
    },
  ],

  TopMatches: [
    {
      sportType: "Football",
      leagues: [
        "England Premier League",
        "England EFL Cup",
        "International Clubs UEFA Champions League",
        "International Africa Cup of Nations",
        "International Euro Cup",
        "Spain Laliga",
        "Italy Series A",
      ],
      odds: [
        "Over/Under",
        "Draw No Bet",
        "3 Way & O/U",
        "Total Goals",
        "Double Chance",
        "Handicapped",
      ],
      sportsLeagues: [
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 57,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 58,
              time: "00:24",
              teamOne: "Equatorial Guinea",
              teamTwo: "South African",
              teamOneScore: "0",
              teamTwoScore: "3",
              home: "2",
              draw: "1.7",
              away: "2.1",
            },
          ],
        },
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 59,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 60,
              time: "08:00",
              teamOne: "Namibia",
              teamTwo: "Moroco",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "2.2",
            },
            {
              id: 61,
              time: "06:00",
              teamOne: "Mail",
              teamTwo: "DR Congo",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 62,
              time: "11:23",
              teamOne: "Nigeria",
              teamTwo: "Moroco",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Fri Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 63,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 64,
              time: "21:23",
              teamOne: "Guinea",
              teamTwo: "Egypt",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "3.0",
              draw: "1.0",
              away: "2.23",
            },
          ],
        },
        {
          leagueName: "International Euro Cup",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 65,
              time: "00:23",
              teamOne: "Switzerland",
              teamTwo: "Germany",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 66,
              time: "00:24",
              teamOne: "Scotland",
              teamTwo: "Hungary",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "International Euro Cup",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 67,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "International Euro Cup",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 68,
              time: "08:00",
              teamOne: "Croatia",
              teamTwo: "Italy",
              teamOneScore: "1",
              teamTwoScore: "0",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 69,
              time: "06:00",
              teamOne: "Spain",
              teamTwo: "Albania",
              teamOneScore: "4",
              teamTwoScore: "2",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 70,
              time: "11:23",
              teamOne: "Denmark",
              teamTwo: "England",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },
        {
          leagueName: "England Premier League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 71,
              time: "00:23",
              teamOne: "Switzerland",
              teamTwo: "Germany",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 72,
              time: "00:24",
              teamOne: "Scotland",
              teamTwo: "Hungary",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "England Premier League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 73,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "England Premier League",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 74,
              time: "08:00",
              teamOne: "Croatia",
              teamTwo: "Italy",
              teamOneScore: "1",
              teamTwoScore: "0",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 75,
              time: "06:00",
              teamOne: "Spain",
              teamTwo: "Albania",
              teamOneScore: "4",
              teamTwoScore: "2",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 76,
              time: "11:23",
              teamOne: "Denmark",
              teamTwo: "England",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },
        {
          leagueName: "England EFL Cup",
          date: "Fri Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 77,
              time: "19:45",
              teamOne: "Arsenal",
              teamTwo: "Manchester City",
              teamOneScore: "1",
              teamTwoScore: "2",
              home: "2.3",
              draw: "3.4",
              away: "2.5",
            },
            {
              id: 78,
              time: "20:21",
              teamOne: "Chelsea",
              teamTwo: "Tottenham Hotspur",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "1.8",
              draw: "3.0",
              away: "3.2",
            },
          ],
        },
        {
          leagueName: "Spain Laliga",
          date: "Fri Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 79,
              time: "18:30",
              teamOne: "Barcelona",
              teamTwo: "Real Madrid",
              teamOneScore: "3",
              teamTwoScore: "1",
              home: "1.9",
              draw: "3.2",
              away: "4.0",
            },
            {
              id: 80,
              time: "19:00",
              teamOne: "Atletico Madrid",
              teamTwo: "Sevilla",
              teamOneScore: "1",
              teamTwoScore: "1",
              home: "2.0",
              draw: "3.0",
              away: "3.5",
            },
          ],
        },
        {
          leagueName: "Italy Series A",
          date: "Fri Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 81,
              time: "17:00",
              teamOne: "Juventus",
              teamTwo: "AC Milan",
              teamOneScore: "2",
              teamTwoScore: "2",
              home: "2.2",
              draw: "2.8",
              away: "3.0",
            },
            {
              id: 82,
              time: "18:00",
              teamOne: "Inter Milan",
              teamTwo: "Napoli",
              teamOneScore: "3",
              teamTwoScore: "1",
              home: "1.8",
              draw: "3.2",
              away: "3.5",
            },
          ],
        },
      ],
    },

    {
      sportType: "Basketball",
      leagues: [
        "NBA",
        "WNBA",
        "NBA G League",
        "NBA 2K League",
        "Basketball Africa League",
      ],
      odds: ["Over/Under", "Draw No Bet", "Double Chance", "Handicapped"],
      sportsLeagues: [
        {
          leagueName: "NBA",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 83,
              time: "00:23",
              teamOne: "Caltics",
              teamTwo: "Bucks",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 84,
              time: "00:24",
              teamOne: "76ers",
              teamTwo: "Knicks",
              teamOneScore: "0",
              teamTwoScore: "3",
              home: "2",
              draw: "1.7",
              away: "2.1",
            },
          ],
        },
        {
          leagueName: "NBA",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 85,
              time: "00:23",
              teamOne: "Cavailiers",
              teamTwo: "Pacers",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "NBA",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 86,
              time: "08:00",
              teamOne: "Heat",
              teamTwo: "Magic",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "2.2",
            },
            {
              id: 87,
              time: "06:00",
              teamOne: "Bulls",
              teamTwo: "Hawks",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 88,
              time: "11:23",
              teamOne: "Raptors",
              teamTwo: "Hormets",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "NBA",
          id: 82,

          date: "Fri Jan 4 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 89,
              time: "00:23",
              teamOne: "Parces",
              teamTwo: "Cavailiers",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 90,
              time: "21:23",
              teamOne: "Magic",
              teamTwo: "Heat",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "3.0",
              draw: "1.0",
              away: "2.23",
            },
            {
              id: 91,
              time: "21:23",
              teamOne: "Wizards",
              teamTwo: "Pistons",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "3.0",
              draw: "1.0",
              away: "2.23",
            },
          ],
        },
        {
          leagueName: "WNBA",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 92,
              time: "21:05",
              teamOne: "Washington Mystics",
              teamTwo: "New York Liberty W",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 93,
              time: "21:24",
              teamOne: "Connecticut Sun W",
              teamTwo: "Indiana Fever W",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "WNBA",
          date: "Thu Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 94,
              time: "08:00",
              teamOne: "Las Vegas Aces W",
              teamTwo: "Phonenix Mercury W",
              teamOneScore: "1",
              teamTwoScore: "0",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 95,
              time: "06:00",
              teamOne: "Seattle Storm W",
              teamTwo: "Minnesota Lynx W",
              teamOneScore: "4",
              teamTwoScore: "2",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 96,
              time: "11:23",
              teamOne: "Dallas Wings W",
              teamTwo: "Chicago Sky W",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },

        {
          leagueName: "NBA G League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 97,
              time: "00:23",
              teamOne: "Minnesota Lynx W",
              teamTwo: "Seatle Storm",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 98,
              time: "00:24",
              teamOne: "Atlanta Dream",
              teamTwo: "Dallas Wing",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "NBA G League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 99,
              time: "00:23",
              teamOne: "Grand Rapids Gold",
              teamTwo: "Motor City Cruise",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "NBA G League",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 100,
              time: "08:00",
              teamOne: "Wisconsin Herd",
              teamTwo: "Windy City Bulls",
              teamOneScore: "22",
              teamTwoScore: "20",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 101,
              time: "06:00",
              teamOne: "Motor City Cruise",
              teamTwo: "Lowa Wolves",
              teamOneScore: "12",
              teamTwoScore: "10",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 102,
              time: "11:23",
              teamOne: "College Park Skyhawks",
              teamTwo: "Delaware Blue Coats",
              teamOneScore: "32",
              teamTwoScore: "11",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },
        {
          leagueName: "NBA 2K League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 103,
              time: "13:00",
              teamOne: "Warriors Gamming Squad",
              teamTwo: "T-Wolves Gaming",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "1.1",
              draw: "2.0",
              away: "1.5",
            },
            {
              id: 104,
              time: "17:30",
              teamOne: "Arsenal",
              teamTwo: "Pistons GT",
              teamOneScore: "1",
              teamTwoScore: "2",
              home: "1.2",
              draw: "0.0",
              away: "1.0",
            },
            {
              id: 105,
              time: "19:30",
              teamOne: "Pacers Gaming",
              teamTwo: "Gizz Gaming",
              teamOneScore: "2",
              teamTwoScore: "2",
              home: "1.20",
              draw: "5.0",
              away: "4.5",
            },
            {
              id: 106,
              time: "17:30",
              teamOne: "Dux Infinitos",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "1.2",
              draw: "0.0",
              away: "1.0",
            },
            {
              id: 107,
              time: "20:00",
              teamOne: "Lakers Gaming",
              teamTwo: "Kings Guard Gaming",
              teamOneScore: "7",
              teamTwoScore: "0",
              home: "2.3",
              draw: "4.0",
              away: "3.5",
            },
          ],
        },
        {
          leagueName: "NBA 2K League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 108,
              time: "00:00",
              teamOne: "Galatasaray",
              teamTwo: "BSC Young Boys",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 109,
              time: "00:00",
              teamOne: "SSC Napoli",
              teamTwo: "Braga",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },

        {
          leagueName: "Basketball Africa League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 110,
              time: "13:00",
              teamOne: "Petro Atletico",
              teamTwo: "Al Ahly",
              teamOneScore: "28",
              teamTwoScore: "12",
              home: "1.1",
              draw: "2.0",
              away: "1.5",
            },
            {
              id: 111,
              time: "17:30",
              teamOne: "SLAC",
              teamTwo: "City Oiler",
              teamOneScore: "1",
              teamTwoScore: "2",
              home: "1.2",
              draw: "0.0",
              away: "1.0",
            },
          ],
        },
        {
          leagueName: "Basketball Africa League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 112,
              time: "00:00",
              teamOne: "Douanes",
              teamTwo: "RES",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 113,
              time: "00:00",
              teamOne: "Abidjan",
              teamTwo: "Monastir",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
      ],
    },
  ],

  UpcomingMatches: [
    {
      sportType: "Football",
      leagues: [
        "England Premier League",
        "England EFL Cup",
        "International Clubs UEFA Champions League",
        "International Africa Cup of Nations",
        "International Euro Cup",
        "Spain Laliga",
        "Italy Series A",
      ],
      odds: [
        "Over/Under",
        "Draw No Bet",
        "3 Way & O/U",
        "Total Goals",
        "Double Chance",
        "Handicapped",
      ],
      sportsLeagues: [
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 114,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 115,
              time: "00:24",
              teamOne: "Equatorial Guinea",
              teamTwo: "South African",
              teamOneScore: "0",
              teamTwoScore: "3",
              home: "2",
              draw: "1.7",
              away: "2.1",
            },
          ],
        },
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 116,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 117,
              time: "08:00",
              teamOne: "Namibia",
              teamTwo: "Moroco",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "2.2",
            },
            {
              id: 118,
              time: "06:00",
              teamOne: "Mail",
              teamTwo: "DR Congo",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 119,
              time: "11:23",
              teamOne: "Nigeria",
              teamTwo: "Moroco",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "International Clubs UEFA Champions League",
          date: "Fri Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 120,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 121,
              time: "21:23",
              teamOne: "Guinea",
              teamTwo: "Egypt",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "3.0",
              draw: "1.0",
              away: "2.23",
            },
          ],
        },
        {
          leagueName: "International Euro Cup",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 122,
              time: "00:23",
              teamOne: "Switzerland",
              teamTwo: "Germany",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 123,
              time: "00:24",
              teamOne: "Scotland",
              teamTwo: "Hungary",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "International Euro Cup",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 124,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "International Euro Cup",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 125,
              time: "08:00",
              teamOne: "Croatia",
              teamTwo: "Italy",
              teamOneScore: "1",
              teamTwoScore: "0",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 126,
              time: "06:00",
              teamOne: "Spain",
              teamTwo: "Albania",
              teamOneScore: "4",
              teamTwoScore: "2",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 127,
              time: "11:23",
              teamOne: "Denmark",
              teamTwo: "England",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },
        {
          leagueName: "England Premier League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 128,
              time: "00:23",
              teamOne: "Switzerland",
              teamTwo: "Germany",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 129,
              time: "00:24",
              teamOne: "Scotland",
              teamTwo: "Hungary",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "England Premier League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 130,
              time: "00:23",
              teamOne: "Cape Verde",
              teamTwo: "Senegal",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "England Premier League",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 131,
              time: "08:00",
              teamOne: "Croatia",
              teamTwo: "Italy",
              teamOneScore: "1",
              teamTwoScore: "0",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 132,
              time: "06:00",
              teamOne: "Spain",
              teamTwo: "Albania",
              teamOneScore: "4",
              teamTwoScore: "2",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 133,
              time: "11:23",
              teamOne: "Denmark",
              teamTwo: "England",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },
        {
          leagueName: "England EFL Cup",
          date: "Fri Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 134,
              time: "19:45",
              teamOne: "Arsenal",
              teamTwo: "Manchester City",
              teamOneScore: "1",
              teamTwoScore: "2",
              home: "2.3",
              draw: "3.4",
              away: "2.5",
            },
            {
              id: 135,
              time: "20:21",
              teamOne: "Chelsea",
              teamTwo: "Tottenham Hotspur",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "1.8",
              draw: "3.0",
              away: "3.2",
            },
          ],
        },
        {
          leagueName: "Spain Laliga",
          date: "Fri Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 136,
              time: "18:30",
              teamOne: "Barcelona",
              teamTwo: "Real Madrid",
              teamOneScore: "3",
              teamTwoScore: "1",
              home: "1.9",
              draw: "3.2",
              away: "4.0",
            },
            {
              id: 137,
              time: "19:00",
              teamOne: "Atletico Madrid",
              teamTwo: "Sevilla",
              teamOneScore: "1",
              teamTwoScore: "1",
              home: "2.0",
              draw: "3.0",
              away: "3.5",
            },
          ],
        },
        {
          leagueName: "Italy Series A",
          date: "Fri Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 138,
              time: "17:00",
              teamOne: "Juventus",
              teamTwo: "AC Milan",
              teamOneScore: "2",
              teamTwoScore: "2",
              home: "2.2",
              draw: "2.8",
              away: "3.0",
            },
            {
              id: 139,
              time: "18:00",
              teamOne: "Inter Milan",
              teamTwo: "Napoli",
              teamOneScore: "3",
              teamTwoScore: "1",
              home: "1.8",
              draw: "3.2",
              away: "3.5",
            },
          ],
        },
      ],
    },

    {
      sportType: "Basketball",
      leagues: [
        "NBA",
        "WNBA",
        "NBA G League",
        "NBA 2K League",
        "Basketball Africa League",
      ],
      odds: ["Over/Under", "Draw No Bet", "Double Chance", "Handicapped"],
      sportsLeagues: [
        {
          leagueName: "NBA",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 140,
              time: "00:23",
              teamOne: "Caltics",
              teamTwo: "Bucks",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 141,
              time: "00:24",
              teamOne: "76ers",
              teamTwo: "Knicks",
              teamOneScore: "0",
              teamTwoScore: "3",
              home: "2",
              draw: "1.7",
              away: "2.1",
            },
          ],
        },
        {
          leagueName: "NBA",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 142,
              time: "00:23",
              teamOne: "Cavailiers",
              teamTwo: "Pacers",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "NBA",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 143,
              time: "08:00",
              teamOne: "Heat",
              teamTwo: "Magic",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "2.2",
            },
            {
              id: 144,
              time: "06:00",
              teamOne: "Bulls",
              teamTwo: "Hawks",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 145,
              time: "11:23",
              teamOne: "Raptors",
              teamTwo: "Hormets",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "3",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "NBA",
          date: "Fri Jan 4 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 146,
              time: "00:23",
              teamOne: "Parces",
              teamTwo: "Cavailiers",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 147,
              time: "21:23",
              teamOne: "Magic",
              teamTwo: "Heat",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "3.0",
              draw: "1.0",
              away: "2.23",
            },
            {
              id: 148,
              time: "21:23",
              teamOne: "Wizards",
              teamTwo: "Pistons",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "3.0",
              draw: "1.0",
              away: "2.23",
            },
          ],
        },
        {
          leagueName: "WNBA",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 149,
              time: "21:05",
              teamOne: "Washington Mystics",
              teamTwo: "New York Liberty W",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 150,
              time: "21:24",
              teamOne: "Connecticut Sun W",
              teamTwo: "Indiana Fever W",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "WNBA",
          date: "Thu Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 151,
              time: "08:00",
              teamOne: "Las Vegas Aces W",
              teamTwo: "Phonenix Mercury W",
              teamOneScore: "1",
              teamTwoScore: "0",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 152,
              time: "06:00",
              teamOne: "Seattle Storm W",
              teamTwo: "Minnesota Lynx W",
              teamOneScore: "4",
              teamTwoScore: "2",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 153,
              time: "11:23",
              teamOne: "Dallas Wings W",
              teamTwo: "Chicago Sky W",
              teamOneScore: "4",
              teamTwoScore: "0",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },

        {
          leagueName: "NBA G League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 154,
              time: "00:23",
              teamOne: "Minnesota Lynx W",
              teamTwo: "Seatle Storm",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "3",
              draw: "3.4",
              away: "5.23",
            },
            {
              id: 155,
              time: "00:24",
              teamOne: "Atlanta Dream",
              teamTwo: "Dallas Wing",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "2.0",
              draw: "0.0",
              away: "1.9",
            },
          ],
        },
        {
          leagueName: "NBA G League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 156,
              time: "00:23",
              teamOne: "Grand Rapids Gold",
              teamTwo: "Motor City Cruise",
              teamOneScore: "2",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
        {
          leagueName: "NBA G League",
          date: "Thu Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 157,
              time: "08:00",
              teamOne: "Wisconsin Herd",
              teamTwo: "Windy City Bulls",
              teamOneScore: "22",
              teamTwoScore: "20",
              home: "4.0",
              draw: "1.4",
              away: "3.5",
            },
            {
              id: 158,
              time: "06:00",
              teamOne: "Motor City Cruise",
              teamTwo: "Lowa Wolves",
              teamOneScore: "12",
              teamTwoScore: "10",
              home: "1.0",
              draw: "2",
              away: "1.5",
            },
            {
              id: 159,
              time: "11:23",
              teamOne: "College Park Skyhawks",
              teamTwo: "Delaware Blue Coats",
              teamOneScore: "32",
              teamTwoScore: "11",
              home: "2.0",
              draw: "1.6",
              away: "1.43",
            },
          ],
        },
        {
          leagueName: "NBA 2K League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 160,
              time: "13:00",
              teamOne: "Warriors Gamming Squad",
              teamTwo: "T-Wolves Gaming",
              teamOneScore: "2",
              teamTwoScore: "0",
              home: "1.1",
              draw: "2.0",
              away: "1.5",
            },
            {
              id: 161,
              time: "17:30",
              teamOne: "Arsenal",
              teamTwo: "Pistons GT",
              teamOneScore: "1",
              teamTwoScore: "2",
              home: "1.2",
              draw: "0.0",
              away: "1.0",
            },
            {
              id: 162,
              time: "19:30",
              teamOne: "Pacers Gaming",
              teamTwo: "Gizz Gaming",
              teamOneScore: "2",
              teamTwoScore: "2",
              home: "1.20",
              draw: "5.0",
              away: "4.5",
            },
            {
              id: 163,
              time: "17:30",
              teamOne: "Dux Infinitos",
              teamOneScore: "0",
              teamTwoScore: "0",
              home: "1.2",
              draw: "0.0",
              away: "1.0",
            },
            {
              id: 164,
              time: "20:00",
              teamOne: "Lakers Gaming",
              teamTwo: "Kings Guard Gaming",
              teamOneScore: "7",
              teamTwoScore: "0",
              home: "2.3",
              draw: "4.0",
              away: "3.5",
            },
          ],
        },
        {
          leagueName: "NBA 2K League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 165,
              time: "00:00",
              teamOne: "Galatasaray",
              teamTwo: "BSC Young Boys",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 166,
              time: "00:00",
              teamOne: "SSC Napoli",
              teamTwo: "Braga",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },

        {
          leagueName: "Basketball Africa League",
          date: "Web Feb 22 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 167,
              time: "13:00",
              teamOne: "Petro Atletico",
              teamTwo: "Al Ahly",
              teamOneScore: "28",
              teamTwoScore: "12",
              home: "1.1",
              draw: "2.0",
              away: "1.5",
            },
            {
              id: 168,
              time: "17:30",
              teamOne: "SLAC",
              teamTwo: "City Oiler",
              teamOneScore: "1",
              teamTwoScore: "2",
              home: "1.2",
              draw: "0.0",
              away: "1.0",
            },
          ],
        },
        {
          leagueName: "Basketball Africa League",
          date: "Web Feb 23 2024 23:05:49 GMT+0100",
          availableMatch: [
            {
              id: 169,
              time: "00:00",
              teamOne: "Douanes",
              teamTwo: "RES",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
            {
              id: 170,
              time: "00:00",
              teamOne: "Abidjan",
              teamTwo: "Monastir",
              teamOneScore: "8",
              teamTwoScore: "3",
              home: "1",
              draw: "1.4",
              away: "1.23",
            },
          ],
        },
      ],
    },
  ],
};
