export const ODDS_DATA = [
  {
    title: "1 x 2",
    odds: [
      { title: "Home", odd: "3.00" },
      { title: "Draw", odd: "1.40" },
      { title: "Away", odd: "2.23" },
    ],
  },
  {
    title: "Over/Under",
    odds: [
      { title: "Over 0.5", odd: "3.00" },
      { title: "Draw", odd: "1.40" },
      { title: "Away", odd: "2.23" },
    ],
  },
];

export const LINK_GAME_TYPES = [
  "Home",
  "Football",
  "Basketball",
  "Table Tennis",
  "Baseball",
  "Rugby",
  "Ice Hockey",
  "Volleyball",
  "Darts",
  "Handball",
];


export const GAME_ODDS = [
  {
    id: 170,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "Over/Under",
    winOdd: "Home",
    winType: 3.00,
    drawOdd: "Draw",
    drawType: 1.40,
    loseOdd: "Away",
    loseType: 2.23,
  },
  {
    id: 171,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "Over/Under",
    winOdd: "Over 0.5",
    winType: 3.00,
    drawOdd: "Under 0.5",
    drawType: 1.50,
  },
  {
    id: 172,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "Over/Under",
    winOdd: "Over 1",
    winType: 5.00,
    drawOdd: "Under 1",
    drawType: 1.80,
  },
  {
    id: 173,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "1st Goal",
    winOdd: "Home",
    winType: 7.00,
    drawOdd: "None",
    drawType: 1.40,
    loseOdd: "Away",
    loseType: 2.23,
  },
  {
    id: 174,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "Handicapped 0:1",
    winOdd: "Home(0.1)",
    winType: 3.00,
    drawOdd: "Draw(0:1)",
    drawType: 1.40,
    loseOdd: "Away(0:1)",
    loseType: 2.23,
  },
  {
    id: 175,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "Handicapped 0:2",
    winOdd: "Home(0:2)",
    winType: 3.00,
    drawOdd: "Draw(0:2)",
    drawType: 1.40,
    loseOdd: "Away(0:2)",
    loseType: 2.23,
  },
  {
    id: 176,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "GG/NG",
    drawOdd: "Yes",
    drawType: 3.00,
    loseOdd: "No",
    loseType: 2.23,
  },
  {
    id: 177,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "1x2",
    winOdd: "Home",
    winType: 3.00,
    drawOdd: "Draw",
    drawType: 1.40,
    loseOdd: "Away",
    loseType: 2.23,
  },
  {
    id: 178,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "Handicapped 0:2",
    winOdd: "Home(0:2)",
    winType: 3.00,
    drawOdd: "Draw(0:2)",
    drawType: 1.40,
    loseOdd: "Away(0:2)",
    loseType: 2.23,
  },
  {
    id: 179,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "1x2",
    winOdd: "Home(0:2)",
    winType: 3.00,
    drawOdd: "Draw(0:2)",
    drawType: 1.40,
    loseOdd: "Away(0:2)",
    loseType: 2.23,
  },
  {
    id: 180,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "1x2",
    winOdd: "Home(0:2)",
    winType: 3.00,
    drawOdd: "Draw(0:2)",
    drawType: 1.40,
    loseOdd: "Away(0:2)",
    loseType: 2.23,
  },
  {
    id: 181,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "1x2",
    winOdd: "Home(0:2)",
    winType: 3.00,
    drawOdd: "Draw(0:2)",
    drawType: 1.40,
    loseOdd: "Away(0:2)",
    loseType: 2.23,
  },
  {
    id: 182,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "1x2",
    winOdd: "Home(0:2)",
    winType: 3.00,
    drawOdd: "Draw(0:2)",
    drawType: 1.40,
    loseOdd: "Away(0:2)",
    loseType: 2.23,
  },
  {
    id: 183,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "1x2",
    winOdd: "Home(0:2)",
    winType: 3.00,
    drawOdd: "Draw(0:2)",
    drawType: 1.40,
    loseOdd: "Away(0:2)",
    loseType: 2.23,
  },
  {
    id: 184,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "1x2",
    winOdd: "Home(0:2)",
    winType: 3.00,
    drawOdd: "Draw(0:2)",
    drawType: 1.40,
    loseOdd: "Away(0:2)",
    loseType: 2.23,
  },
  {
    id: 185,
    time: "00:23",
    teamOne: "Cape Verde",
    teamTwo: "Senegal",
    title: "1x2",
    winOdd: "Home(0:2)",
    winType: 3.00,
    drawOdd: "Draw(0:2)",
    drawType: 1.40,
    loseOdd: "Away(0:2)",
    loseType: 2.23,
  },
];
